name: Deploy Kubernetes Manifest to AWS EKS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Install kubectl
    - name: Install kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    # Set up kubeconfig for EKS
    - name: Configure kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    # Apply Kubernetes manifests
    - name: Apply Kubernetes Manifests
      run: |
        kubectl create ns nodejs-env || true
        kubectl apply -f deployment.yaml -n nodejs-env
        kubectl apply -f svc.yaml -n nodejs-env
        kubectl apply -f ingress.yaml -n nodejs-env
        kubectl get ns
        kubectl get svc,ing -n nodejs-env


